export const ROUTES = {
    LANDING: '/',
    HOME: '/Home/',
    DETAIL: '/Detail',
    SEARCH:'/Search',
    NAME: '/Home/:name',
    ABOUT: '/About',
    CONTACT: "/contactUs",
    STORE:'/Store',
    CREATEGAME:'/CreateGame',
    CREATEUSER: "/CreateUser",
    PROFILEUSER: "/UserProfile",
    MERCADO: '/Mercado',
    CHECKOUT: '/Checkout',
    SUCCESS: '/Payment-success',
    FAILURE: '/Payment-failure',
    ERROR: '*',
    LOGIN: '/Login',
    CART: '/Cart',
   
}